/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.financ.Telas;

import java.math.BigDecimal;
import java.math.RoundingMode;

/**
 *
 * @author felip
 */
public class IMC extends javax.swing.JFrame {

    /**
     * Creates new form IMC
     */
    public IMC() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        Peso = new javax.swing.JLabel();
        Altura = new javax.swing.JLabel();
        TxtPeso = new javax.swing.JTextField();
        TxtAltura = new javax.swing.JTextField();
        Calcular = new javax.swing.JButton();
        lblExibir = new javax.swing.JLabel();
        RadMen = new javax.swing.JRadioButton();
        RadWoman = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitulo.setText("IMC");

        Peso.setText("Peso :");

        Altura.setText("Altura :");

        Calcular.setText("Calcular");
        Calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalcularActionPerformed(evt);
            }
        });

        RadMen.setText("Homem");
        RadMen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadMenActionPerformed(evt);
            }
        });

        RadWoman.setText("Mulher");
        RadWoman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadWomanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(256, 256, 256)
                        .addComponent(lblTitulo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(Peso)
                                        .addGap(18, 18, 18))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Altura)
                                        .addGap(11, 11, 11)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(TxtAltura, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                                    .addComponent(TxtPeso)))
                            .addComponent(Calcular)
                            .addComponent(lblExibir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RadMen)
                            .addComponent(RadWoman))))
                .addContainerGap(266, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblTitulo)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Peso)
                    .addComponent(TxtPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RadMen))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Altura)
                    .addComponent(TxtAltura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RadWoman))
                .addGap(28, 28, 28)
                .addComponent(Calcular)
                .addGap(18, 18, 18)
                .addComponent(lblExibir, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(164, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalcularActionPerformed
     try{
         double Altura  = Double.parseDouble(TxtAltura.getText());
         int Peso = Integer.parseInt(TxtPeso.getText());
         if(Altura > 100){
             Altura = Altura/100;
         }
        
         
         String texto = null;
         double imc = (Peso/(Altura * Altura));
         BigDecimal imcGG = new BigDecimal(imc);
         
         if(RadWoman.isSelected()){
         if(imc < 20.7){
             texto = "abaixo do peso";
         }else if(20.7 >= imc && imc < 26.4){
            texto = "dentro do peso normal"; 
         }else if(26.4 >= imc && imc < 27.8){
            texto = "marginalmente acima do peso"; 
         }else if(27.8 >= imc && imc < 31.1){
            texto = "acima do peso"; 
         }else if(imc > 31.1){
            texto = "obeso"; 
         }
         }else if(RadMen.isSelected()){
             if(imc < 19.1){
             texto = "abaixo do peso";
         }else if(19.1 >= imc && imc < 25.8){
            texto = "dentro do peso normal"; 
         }else if(25.8 >= imc && imc < 27.3){
            texto = "marginalmente acima do peso"; 
         }else if(27.3 >= imc && imc < 32.3){
            texto = "acima do peso"; 
         }else if(imc > 32.3){
            texto = "obeso"; 
         }
         }
         lblExibir.setText("Seu imc é : "+imcGG.setScale(4, RoundingMode.CEILING)+" e você está "+texto);
     }catch (Exception ex ){
         System.out.println(ex.getMessage());
     }
    }//GEN-LAST:event_CalcularActionPerformed

    private void RadMenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadMenActionPerformed
       if(RadMen.isSelected()){
          RadWoman.setSelected(false);
          
      }
    }//GEN-LAST:event_RadMenActionPerformed

    private void RadWomanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadWomanActionPerformed
       if(RadWoman.isSelected()){
          RadMen.setSelected(false);
          
      }
    }//GEN-LAST:event_RadWomanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IMC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IMC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IMC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IMC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IMC().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Altura;
    private javax.swing.JButton Calcular;
    private javax.swing.JLabel Peso;
    private javax.swing.JRadioButton RadMen;
    private javax.swing.JRadioButton RadWoman;
    private javax.swing.JTextField TxtAltura;
    private javax.swing.JTextField TxtPeso;
    private javax.swing.JLabel lblExibir;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables
}
